# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.7

stages:
  - lint
  - test
  - analysis
  - build
  - push

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

# To get Django tests to work you may need to create a settings file using
# the following DATABASES:
#
# DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'ci',
#        'USER': 'postgres',
#        'PASSWORD': 'postgres',
#        'HOST': 'postgres',
#        'PORT': '5432',
#    },
# }
#
# and then adding `--settings app.settings.ci` (or similar) to the test command


py_lint:
  stage: lint
  before_script:
    - pip install requirements.txt
    - pip install pylint
  script:
    - pylint devops
  tags:
    - default-docker
  except:
    - master
  allow_failure: true

py_test:
  stage: test
  services:
    - mysql:5.7
  variables:
    MYSQL_ROOT_PASSWORD: "testpassword"
    MYSQL_DATABASE: "devops"
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test
  tags:
    - default-docker
  except:
    - master

py_sast:
  stage: analysis
  before_script:
    - pip install bandit
  script:
    - bandit -r ./config ./devops
  tags:
    - default-docker
  allow_failure: true
  except:
    - master

py_dast:
  image: docker:latest
  stage: analysis
  script:
    - docker-compose up -d
    - docker logs -f zap
    - docker-compose down
  tags:
    - default-shell
  except:
    - master

docker_build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
  tags:
    - default-shell
  only:
    - master

docker_push:
  stage: push
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker push "$CI_REGISTRY_IMAGE"
  tags:
    - default-shell
  only:
    - master
