# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.7

stages:
  - lint
  - test
  - merge
  - docker-build

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python -V  # Print out python version for debugging
  # Uncomment next line if your Django app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - pip install -r requirements.txt

# To get Django tests to work you may need to create a settings file using
# the following DATABASES:
#
# DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'ci',
#        'USER': 'postgres',
#        'PASSWORD': 'postgres',
#        'HOST': 'postgres',
#        'PORT': '5432',
#    },
# }
#
# and then adding `--settings app.settings.ci` (or similar) to the test command


py_lint:
  stage: lint
  script:
    - pylint devops
  tags:
    - default-docker
  only:
    - branch

py_test:
  stage: test
  services:
    - mysql:5.7
  variables:
    MYSQL_ROOT_PASSWORD: "testpassword"
    MYSQL_DATABASE: "devops"
  script:
    - python manage.py test
  tags:
    - default-docker
  only:
    - branch

git_merge:
  stage: merge
  before_script:
    - echo "$CI_COMMIT_BRANCH"
    - echo "$GITLAB_USER_NAME"
  script:
    - pwd
    - git config --list
    - git checkout origin/3-merge-test
    - git checkout master
    - git merge origin/3-merge-test
  tags:
    - default-docker
  when: manual
  only:
    refs:
      - branches

docker_build:
  image: docker:latest
  services:
    - docker:dind
  stage: docker-build
  before_script:
    - docker --version
    - echo "docker login"
  script:
    - echo "docker build"
  tags:
    - default-docker
  only:
    variables:
      - $GITLAB_USER_NAME == "Donkey-1028"
  needs: ["git_merge"]
